### ISSUE TITLE
Bring back old notifier.

### ISSUE THREAD

**Issue by s4yto** [ROBLOX-Plus/Chrome#107]
The notifier is really slow now, despite the new update for the values shown that is cool, its now as slow as rovalk, the old notifier was super fast please

**Comment by s4yto** [comment]
its not even values shown in the nofications as its said, its rap so its really misleading just revert it and get the old notifier back please

**Comment by WebGL3D** [comment]
Unfortunately, with restrictions of the [chrome.alarms](https://developer.chrome.com/docs/extensions/reference/alarms/) API, the notifiers are unable to execute any faster than once/minute. Sorry! :frowning:
