### ISSUE TITLE
MUCH ADWARE AND MALWARE IN THIS.

### ISSUE THREAD

**Issue by MandrakenDEV** [ROBLOX-Plus/Chrome#32]
Malwarebytes detected PUP.Optional.Conduit, PUP.Optional.Ask and PUP.OptionalSearch.ShrtCln, i need a explication. And when i deleted Roblox+, Malwarebytes stoped detections in AppData/Google/Chrome/. I need a fast explication, Malwarebytes detected 37 adwares and browser hijacker.

**Comment by MandrakenDEV** [comment]
And with Windows Defender (Win11) and Bitdefender detected the extension like a PUP, adware and spyware.

**Comment by Overimagine1** [comment]
you probably got a fake version, roblox+ is not a virus
besides its open source, you can see the code of the extension for yourself.

**Comment by MandrakenDEV** [comment]
He descargado la version desde roblox.plus. No se si sea un sitio falso.

**Comment by MandrakenDEV** [comment]
I downloaded Roblox+ from https://roblox.plus/. (aka: https://chrome.google.com/webstore/detail/roblox%20/jfbnmfgkohlfclfnplnlenbalpppohkm) IDK if that is fake site.

**Comment by MandrakenDEV** [comment]
And my apologies for my anger, I was very stressed that day and I got even more stressed seeing that my preferred extension for Roblox was with a lot of adware and hijackers.

**Comment by MandrakenDEV** [comment]
holy frick, i am dumb, i closed the problem

**Comment by juls0730** [comment]
@MandrakenDEV it seems you reopened this problem (by mistake?) if this is no longer a problem please close the issue

**Comment by WebGL3D** [comment]
Leaving this open until maybe someday I investigate why your antivirus software is/was detecting this as a malware. The extension is published out of this repository, and has no form of advertising in the extension.
