### ISSUE TITLE
Roblox+ icon isn't visible on the top right

### ISSUE THREAD

**Issue by xSting7** [ROBLOX-Plus/Chrome#35]
The Roblox+ icon isn't visible on the top bar on the top right (Beside the Roblox settings icon). You have to click it to open or close the box which shows a player's limited items on their but there's no way now to see that . I have tried disabling and re-enabling the extension, removing it and adding it again on multiple browsers but it's still not there.

![Screenshot 2021-12-16 235634](https://user-images.githubusercontent.com/68888117/146427891-55e03896-616b-454f-bdf3-044d405729d7.png)

**Comment by WebGL3D** [comment]
Reopening until the extension is published with the fix.
