### ISSUE TITLE
Server hoping 

### ISSUE THREAD

**Issue by OrateMA** [ROBLOX-Plus/Chrome#39]
Every single time I try to server hop in an unpopulated server, it wouldn't let me do the shortcut. So every time I look at the server list, it doesn't show the shortcut where you can skip servers by numbers. Instead, it shows the regular "load more" button to load more servers. I don't know if it is the game but I am sure it is not just me. Please explain

**Comment by idkxD1** [comment]
I think today, Developer Roblox have just updated something about Server tab so the Skip pager doesnt work. Just waiting for another version of Roblox+ to fix this problem.

**Comment by OrateMA** [comment]
I see. How long would the problem be fix is the real question
