### ISSUE TITLE
Typos in My Settings page

### ISSUE THREAD

**Issue by 22pool** [ROBLOX-Plus/Chrome#41]
There are 2 slight typos in the Other tab of the My Settings page.

**Firstly:**
![image](https://user-images.githubusercontent.com/88901741/159199296-3f1fc3d0-c65b-4a33-9220-3ca0fe727723.png)
This heading says "Display users RAP in header." But should say "Display user**s'** RAP in header."

![image](https://user-images.githubusercontent.com/88901741/159199389-1b96310f-6d50-4bc6-a245-fab1a41bdf88.png)
An example image for what it should look like.

**Secondly:**
![image](https://user-images.githubusercontent.com/88901741/159199435-6533cf0f-90a5-4b10-900c-6a49c08ac435.png)
The heading here says "Track of joined servers." which doesn't make sense and should instead say either "Keep track of joined servers." or "Track joined servers."

![image](https://user-images.githubusercontent.com/88901741/159199579-5104fda7-9bf7-4c6d-8e9f-54a9b6b238b3.png)
The first option.
![image](https://user-images.githubusercontent.com/88901741/159199550-fbff1505-1b9b-4a75-8084-d08587c2438e.png)
The second option

**Comment by WebGL3D** [comment]
This should be resolved. :sweat_smile:
