### ISSUE TITLE
For games, I can't immediately go to the last page.

### ISSUE THREAD

**Issue by deno002** [ROBLOX-Plus/Chrome#42]
So I usually could press a button that just skipped to the last page, but recently it has disappeared, I don't know if this is a new update but what was there isn't anymore. I checked settings and couldnt find any setting to fix it.
![Screenshot (111)](https://user-images.githubusercontent.com/102009439/159204792-fbdc9c61-5763-4cf8-9688-0dfebf1d627f.png)

**Comment by TodgerBG** [comment]
I have the same issue

**Comment by dveak** [comment]
It's not a bug, check the changes he committed 27 days ago.
There's a whole section related to this feature that was just deleted for an unknown reason.

EDIT: https://github.com/roblox-plus/Chrome/pull/38

**Comment by WebGL3D** [comment]
This was indeed an intentional decision, and then Roblox published an update in the summer last year which replaced the game server paging feature.

As a result, the feature will not return to Roblox+ (because it is built into Roblox now).

Thanks for the report though.
