### ISSUE TITLE
Incorrect servers being shown

### ISSUE THREAD

**Issue by SkyboundStars** [ROBLOX-Plus/Chrome#47]
When browsing the servers, wanting to get into the smallest server etc, it will start showing small servers as requested. its just that 99% of those are private servers which u wont have access to (gives error code 524). This makes it a tedious task finding a small server that u can actually join.

**Comment by WebGL3D** [comment]
Can you confirm if this was fixed?

**Comment by SkyboundStars** [comment]
As far as I've seen, there are no problems anymore, so I confirm. Thanks!
