### ISSUE TITLE
Profile RAP display not working as intended

### ISSUE THREAD

**Issue by vinceingithub** [ROBLOX-Plus/Chrome#48]
When viewing someone's RAP on their profile, typically clicking the link would open a little menu of all their limited items and their RAP. As of recently, this feature hasn't worked and clicking the RAP does nothing. When attempting to open the link in a new tab, its takes me to "about:blank#blocked". Not sure if this is an issue with my browser's settings or the plugin, assuming the latter.

**Comment by WebGL3D** [comment]
Will be fixed the next time the extension is published. Thank you for the report.
