### ISSUE TITLE
Premium API not working

### ISSUE THREAD

**Issue by alreadypro** [ROBLOX-Plus/Chrome#54]
I have a Private Server for the [Roblox+ Premium Hub](url) that has been active for years. For the past month, I have not been receiving my Roblox+ Premium benefits.

This feature broke on or around **January 3rd, 2023** when [Roblox replaced the Vip Server List Endpoint](https://devforum.roblox.com/t/vip-server-list-endpoint-replacement/2078385) from

`https://games.roblox.com/v1/games/{placeId}/servers/vip` -> `https://games.roblox.com/v1/games/{placeId}/private-servers`

<details>
<summary>Sidenote</summary>
The appended "/vip" to the former API is now ignored, which is why the requests to that endpoint return a 200 response code rather than a 404, a bad move on Roblox's part and inconsistent with similar behavior on the updated endpoint.
  
  

[correct usage \(/private-servers\)](https://games.roblox.com/v1/games/258257446/private-servers)
vs
[incorrect usage \(/private-servers/THIS_IS_INVALID\)](https://games.roblox.com/v1/games/258257446/private-servers/THIS_IS_INVALID)
</details>

The backend of Roblox Plus needs to update the Roblox+ Premium API endpoint at
`https://api.roblox.plus/v1/rpluspremium/{userId}` to use the updated Vip Server API endpoint.

**Comment by WebGL3D** [comment]
Fixed, and published. Thank you for the detailed report.

Sorry for the delay on this one.
