### ISSUE TITLE
Robux "amount" getting changed

### ISSUE THREAD

**Issue by Rutger505** [ROBLOX-Plus/Chrome#60]
So, I found this weird issue, I have 8067 robux and when I click on it (to reveal dropdown with buy robux) the robux is set to 8. When I refresh the page, it shows 8067 robux again. Here are the screenshots. 

![image](https://user-images.githubusercontent.com/119070855/230926124-6235b6d2-7884-4595-a123-497a6dcb6813.png)
![image](https://user-images.githubusercontent.com/119070855/230926157-0501aa43-caf2-4824-9069-9da780f4f5dd.png)

I verified the problem is with this extension by turning it off and on.

**Comment by WebGL3D** [comment]
Should have been fixed by #75 - please confirm. :pray:

**Comment by Rutger505** [comment]
Hmm i'm sorry to say but after this post i was not able to recreate this bug. I tried this again just now and nothing special happend. So sorry i can not confirm it is fixed.

**Comment by WebGL3D** [comment]
I'm going to consider this issue fixed then, thanks!
