### ISSUE TITLE
Roblox+ is disabled.

### ISSUE THREAD

**Issue by JP-STHS** [ROBLOX-Plus/Chrome#77]
Was working fine until some new update allows the extension to block content on any page...?
Is the extension still good to use?

![image](https://user-images.githubusercontent.com/132488861/236633198-9f820d7c-b0ec-4fd6-a5db-990ec1b3e2fc.png)

**Comment by WebGL3D** [comment]
Yes, this is expected. I understand the concern, and I try to avoid updating the permissions, but it was necessary following #74. #74 started moving the extension from [chrome.webRequest](https://developer.chrome.com/docs/extensions/reference/webRequest/) -> [chrome.declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/) - so the extension can be service worker compatible. Apparently that new permission shows up as being able to block content on any page. :see_no_evil:

**Comment by JP-STHS** [comment]
Thanks for the reply.
Solves all my concerns!
