### ISSUE TITLE
Vote percentage spam

### ISSUE THREAD

**Issue by KelvenOne** [ROBLOX-Plus/Chrome#83]
For some reason, there are tons of vote percentage elements being created each second...

![image](https://github.com/roblox-plus/extension/assets/59834219/1826f5f1-0578-4006-bb5d-3f47bdf72e81)

**Comment by WebGL3D** [comment]
Reproduces on games with less than 1,000 votes on both sides.
Example: [Bloxel](https://www.roblox.com/games/1427028360/Bloxel)

I understand why, and will have a fix in the next update. Thank you.
